In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#One-hot encoding 'Geography"

Onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = Onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=Onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(Onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64,activation='relu', input_shape = (X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])


model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

c:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model

history = model.fit(
    X_train, y_train ,
    validation_data = (X_test,y_test),
    epochs = 100,
    callbacks = [early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 100231.6641 - mae: 100231.6641 - val_loss: 98583.8516 - val_mae: 98583.8516
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100178.3125 - mae: 100178.3125 - val_loss: 97488.9062 - val_mae: 97488.9062
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98591.8594 - mae: 98591.8594 - val_loss: 94609.2031 - val_mae: 94609.2031
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95838.2422 - mae: 95838.2422 - val_loss: 89636.3047 - val_mae: 89636.3047
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 89498.5156 - mae: 89498.5156 - val_loss: 82859.3516 - val_mae: 82859.3516
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83504.9375 - mae: 83504.9375 - val_loss: 75036.4688 - val_mae: 75036.4688
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74015.9531 - mae: 74015.9531 - val_loss: 67460.0000 - val_mae: 67460.0000
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 66719.2500 - mae: 66719.2500 - val_loss: 61015.5898 - val_mae: 61015.5898
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59309.2656 - mae: 59309.2656 - val_loss: 56307.3086 - val_mae: 56307.3086
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55991.5195 - mae: 55991.5195 - val_loss: 53391.7422 - val_mae: 53391.7422
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52654.8320 - mae: 52654.8320 - val_loss: 51894.4414 - val_mae: 51894.4414
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52034.5820 - mae: 52034.5820 - val_loss: 51301.6992 - val_mae: 51301.6992
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50656.2539 - mae: 50656.2539 - val_loss: 51062.7188 - val_mae: 51062.7188
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50185.1992 - mae: 50185.1992 - val_loss: 50964.6406 - val_mae: 50964.6406
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50376.4336 - mae: 50376.4336 - val_loss: 50902.8828 - val_mae: 50902.8828
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50357.4883 - mae: 50357.4883 - val_loss: 50853.5117 - val_mae: 50853.5117
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50291.9766 - mae: 50291.9766 - val_loss: 50803.5117 - val_mae: 50803.5117
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49777.3594 - mae: 49777.3594 - val_loss: 50758.1914 - val_mae: 50758.1914
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49944.1094 - mae: 49944.1094 - val_loss: 50721.9805 - val_mae: 50721.9805
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50380.4844 - mae: 50380.4844 - val_loss: 50692.7305 - val_mae: 50692.7305
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49673.6133 - mae: 49673.6133 - val_loss: 50661.7109 - val_mae: 50661.7109
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49893.7070 - mae: 49893.7070 - val_loss: 50631.5625 - val_mae: 50631.5625
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49899.4844 - mae: 49899.4844 - val_loss: 50604.5156 - val_mae: 50604.5156
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49819.7227 - mae: 49819.7227 - val_loss: 50586.5117 - val_mae: 50586.5117
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49867.8398 - mae: 49867.8398 - val_loss: 50571.6250 - val_mae: 50571.6250
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49526.0469 - mae: 49526.0469 - val_loss: 50550.7188 - val_mae: 50550.7188
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50137.1953 - mae: 50137.1953 - val_loss: 50538.5781 - val_mae: 50538.5781
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49764.5039 - mae: 49764.5039 - val_loss: 50519.3203 - val_mae: 50519.3203
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49582.6445 - mae: 49582.6445 - val_loss: 50508.5000 - val_mae: 50508.5000
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49228.8984 - mae: 49228.8984 - val_loss: 50483.9023 - val_mae: 50483.9023
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49754.6758 - mae: 49754.6758 - val_loss: 50474.1367 - val_mae: 50474.1367
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50166.3281 - mae: 50166.3281 - val_loss: 50460.1953 - val_mae: 50460.1953
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49528.6758 - mae: 49528.6758 - val_loss: 50448.4883 - val_mae: 50448.4883
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49314.6914 - mae: 49314.6914 - val_loss: 50437.3320 - val_mae: 50437.3320
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49532.4961 - mae: 49532.4961 - val_loss: 50433.1523 - val_mae: 50433.1523
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49412.4102 - mae: 49412.4102 - val_loss: 50416.9531 - val_mae: 50416.9531
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49560.1992 - mae: 49560.1992 - val_loss: 50413.5586 - val_mae: 50413.5586
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50180.2461 - mae: 50180.2461 - val_loss: 50400.1797 - val_mae: 50400.1797
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49563.5508 - mae: 49563.5508 - val_loss: 50393.1055 - val_mae: 50393.1055
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48949.0195 - mae: 48949.0195 - val_loss: 50381.2148 - val_mae: 50381.2148
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49653.9648 - mae: 49653.9648 - val_loss: 50375.9766 - val_mae: 50375.9766
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49581.3125 - mae: 49581.3125 - val_loss: 50365.9844 - val_mae: 50365.9844
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49163.3750 - mae: 49163.3750 - val_loss: 50356.0430 - val_mae: 50356.0430
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49317.2773 - mae: 49317.2773 - val_loss: 50361.1211 - val_mae: 50361.1211
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50275.8477 - mae: 50275.8477 - val_loss: 50349.2422 - val_mae: 50349.2422
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49014.5977 - mae: 49014.5977 - val_loss: 50339.9648 - val_mae: 50339.9648
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49061.8711 - mae: 49061.8711 - val_loss: 50337.9336 - val_mae: 50337.9336
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49046.4062 - mae: 49046.4062 - val_loss: 50342.1953 - val_mae: 50342.1953
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48922.4844 - mae: 48922.4844 - val_loss: 50342.4336 - val_mae: 50342.4336
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49257.5000 - mae: 49257.5000 - val_loss: 50332.0117 - val_mae: 50332.0117
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49067.6641 - mae: 49067.6641 - val_loss: 50348.0352 - val_mae: 50348.0352
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49847.6523 - mae: 49847.6523 - val_loss: 50332.4844 - val_mae: 50332.4844
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48935.8438 - mae: 48935.8438 - val_loss: 50332.9336 - val_mae: 50332.9336
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49249.8711 - mae: 49249.8711 - val_loss: 50330.0586 - val_mae: 50330.0586
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49382.0781 - mae: 49382.0781 - val_loss: 50331.2695 - val_mae: 50331.2695
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49106.1992 - mae: 49106.1992 - val_loss: 50328.7812 - val_mae: 50328.7812
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48897.9297 - mae: 48897.9297 - val_loss: 50334.0938 - val_mae: 50334.0938
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49265.2383 - mae: 49265.2383 - val_loss: 50343.0117 - val_mae: 50343.0117
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48983.6484 - mae: 48983.6484 - val_loss: 50354.6055 - val_mae: 50354.6055
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49586.9844 - mae: 49586.9844 - val_loss: 50342.2031 - val_mae: 50342.2031
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49196.2227 - mae: 49196.2227 - val_loss: 50347.3984 - val_mae: 50347.3984
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49460.8555 - mae: 49460.8555 - val_loss: 50355.5508 - val_mae: 50355.5508
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49270.9453 - mae: 49270.9453 - val_loss: 50352.4297 - val_mae: 50352.4297
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49774.1562 - mae: 49774.1562 - val_loss: 50352.8672 - val_mae: 50352.8672
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49743.6445 - mae: 49743.6445 - val_loss: 50345.7930 - val_mae: 50345.7930
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49161.1484 - mae: 49161.1484 - val_loss: 50347.2969 - val_mae: 50347.2969

In [18]:
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 25140), started 0:00:23 ago. (Use '!kill 25140' to kill it.)

In [21]:
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'TEST MAE:{test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51130.4414 - mae: 51130.4414
TEST MAE:50328.78125

In [22]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.